version: "3"
services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/app/Dockerfile
    image: sf_muni_app:latest
    container_name: sf_muni_app
    ports:
      - "8000:8000"
  redis:
    image: "redis:alpine"
